"""migration - 1: added latitude and longitude column in installations table

Revision ID: a927edb89965
Revises: 
Create Date: 2026-09-25 16:58:55.248708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a927edb89965'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installation')
    op.add_column('installations', sa.Column('latitude', sa.Float(), server_default=sa.text('0.0'), nullable=False))
    op.add_column('installations', sa.Column('longitude', sa.Float(), server_default=sa.text('0.0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installations', 'longitude')
    op.drop_column('installations', 'latitude')
    op.create_table('installation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('installation_pkey'))
    )
    # ### end Alembic commands ###
